//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Alumnos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Alumnos.Practice_1_Create_alumno_Port_1")]
    public interface Practice_1_Create_alumno_Port_1 {
        
        // CODEGEN: Generating message contract since the operation Que_pedo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Que_pedo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.Alumnos.Que_pedoResponse Que_pedo(ConsoleApplication1.Alumnos.Que_pedoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Que_pedo", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.Alumnos.Que_pedoResponse> Que_pedoAsync(ConsoleApplication1.Alumnos.Que_pedoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Practice_1.Request_Alumno")]
    public partial class Request_system : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string apellidosField;
        
        private string edadField;
        
        private Request_systemContactos[] contactosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("Apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("Edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contactos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Request_systemContactos[] Contactos {
            get {
                return this.contactosField;
            }
            set {
                this.contactosField = value;
                this.RaisePropertyChanged("Contactos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Practice_1.Request_Alumno")]
    public partial class Request_systemContactos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string apellidosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("Apellidos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Practice_1.Response_Alumno")]
    public partial class Response_system : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Que_pedoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Practice_1.Request_Alumno", Order=0)]
        public ConsoleApplication1.Alumnos.Request_system Request_system;
        
        public Que_pedoRequest() {
        }
        
        public Que_pedoRequest(ConsoleApplication1.Alumnos.Request_system Request_system) {
            this.Request_system = Request_system;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Que_pedoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Practice_1.Response_Alumno", Order=0)]
        public ConsoleApplication1.Alumnos.Response_system Response_system;
        
        public Que_pedoResponse() {
        }
        
        public Que_pedoResponse(ConsoleApplication1.Alumnos.Response_system Response_system) {
            this.Response_system = Response_system;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Practice_1_Create_alumno_Port_1Channel : ConsoleApplication1.Alumnos.Practice_1_Create_alumno_Port_1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Practice_1_Create_alumno_Port_1Client : System.ServiceModel.ClientBase<ConsoleApplication1.Alumnos.Practice_1_Create_alumno_Port_1>, ConsoleApplication1.Alumnos.Practice_1_Create_alumno_Port_1 {
        
        public Practice_1_Create_alumno_Port_1Client() {
        }
        
        public Practice_1_Create_alumno_Port_1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Practice_1_Create_alumno_Port_1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Practice_1_Create_alumno_Port_1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Practice_1_Create_alumno_Port_1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.Alumnos.Que_pedoResponse ConsoleApplication1.Alumnos.Practice_1_Create_alumno_Port_1.Que_pedo(ConsoleApplication1.Alumnos.Que_pedoRequest request) {
            return base.Channel.Que_pedo(request);
        }
        
        public ConsoleApplication1.Alumnos.Response_system Que_pedo(ConsoleApplication1.Alumnos.Request_system Request_system) {
            ConsoleApplication1.Alumnos.Que_pedoRequest inValue = new ConsoleApplication1.Alumnos.Que_pedoRequest();
            inValue.Request_system = Request_system;
            ConsoleApplication1.Alumnos.Que_pedoResponse retVal = ((ConsoleApplication1.Alumnos.Practice_1_Create_alumno_Port_1)(this)).Que_pedo(inValue);
            return retVal.Response_system;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.Alumnos.Que_pedoResponse> ConsoleApplication1.Alumnos.Practice_1_Create_alumno_Port_1.Que_pedoAsync(ConsoleApplication1.Alumnos.Que_pedoRequest request) {
            return base.Channel.Que_pedoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.Alumnos.Que_pedoResponse> Que_pedoAsync(ConsoleApplication1.Alumnos.Request_system Request_system) {
            ConsoleApplication1.Alumnos.Que_pedoRequest inValue = new ConsoleApplication1.Alumnos.Que_pedoRequest();
            inValue.Request_system = Request_system;
            return ((ConsoleApplication1.Alumnos.Practice_1_Create_alumno_Port_1)(this)).Que_pedoAsync(inValue);
        }
    }
}
